name: dishank_dev_resume_website
description: A new Flutter project.

publish_to: "none"

version: 0.0.2+2

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: any
  url_launcher: any
  firebase_core: any
  firebase_database: any
  image: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/img/
    - asset/img/bg/
    - asset/img/logo/
    - asset/icon/
