name: dishankdev
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18

  # Navigation 2.0 declarative
  auto_route: ^3.2.1

  # Simple Animation looper
  simple_animations: ^4.0.1
  animated_text_kit: ^4.2.1
  auto_size_text: ^3.0.0

  # Firebase
  firebase_core: ^1.11.0
  firebase_app_check: ^0.0.6+4
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/
