name: dishank_dev_resume_website
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/home/
